[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
CI = "true"
NODE_ENV = "production"
VITE_API_URL = "https://srrfarms-backend.onrender.com/api"

# SPA redirect for React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
